sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tRzC7Kbs1vj4eW6feuV
    access-key-secret: ${access-key-secret}
    bucket-name: huangxuanbucket
    endpoint: oss-cn-shanghai.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx90539ad8d6668f77
    secret: d5ce6a56319d4dfe6235bf3a8b1dff5f
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://153a29ba.r7.cpolar.top
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php

